model_params:
  name: 'IWAE'
  in_channels: 3
  latent_dim: 128
  num_samples: 5

exp_params:
  dataset: celeba
  data_path: "../../shared/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.007
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [3]
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "IWAE"
  manual_seed: 1265
