model_params:
  name: 'LVAE'
  in_channels: 3
  latent_dims: [4,8,16,32,128]
  hidden_dims: [32, 64,128, 256, 512]

exp_params:
  dataset: celeba
  data_path: "../../shared/momo/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [2]
  max_nb_epochs: 50
  max_epochs: 30
  gradient_clip_val: .5

logging_params:
  save_dir: "logs/"
  name: "LVAE"
  manual_seed: 1265
