model_params:
  name: 'SWAE'
  in_channels: 3
  latent_dim: 128
  reg_weight: 100
  wasserstein_deg: 2.0
  num_projections: 200
  projection_dist: "normal" #"cauchy"

exp_params:
  dataset: celeba
  data_path: "../../shared/momo/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "SWAE"
  manual_seed: 1265




