model_params:
  name: 'VQVAE'
  in_channels: 3
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25

exp_params:
  dataset: celeba
  data_path: "../../shared/momo/Data/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: [2]
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VQVAE"
  manual_seed: 1265
